# Secret for Microsoft Fabric Analytics MCP Server sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: fabric-mcp-secrets
  namespace: fabric-mcp
  labels:
    app: fabric-analytics-mcp
type: Opaque
stringData:
  # Microsoft Fabric Service Principal Authentication
  # These values should be replaced with actual credentials during deployment
  FABRIC_CLIENT_ID: "your-client-id-here"
  FABRIC_CLIENT_SECRET: "your-client-secret-here"
  FABRIC_TENANT_ID: "your-tenant-id-here"
  
  # Optional: Default workspace for simplified operations
  FABRIC_DEFAULT_WORKSPACE_ID: "your-default-workspace-id"
  
  # Optional: Bearer token for alternative authentication
  FABRIC_BEARER_TOKEN: ""
  
  # Application secrets
  JWT_SECRET: "your-jwt-secret-for-internal-auth"
  API_KEY: "your-api-key-for-internal-services"
---
# Azure Key Vault SecretProviderClass (optional - for Azure Key Vault integration)
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fabric-mcp-secrets-provider
  namespace: fabric-mcp
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "your-managed-identity-client-id"
    keyvaultName: "your-keyvault-name"
    tenantId: "your-tenant-id"
    objects: |
      array:
        - |
          objectName: fabric-client-id
          objectType: secret
          objectVersion: ""
        - |
          objectName: fabric-client-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: fabric-tenant-id
          objectType: secret
          objectVersion: ""
  secretObjects:
  - secretName: fabric-mcp-secrets-from-keyvault
    type: Opaque
    data:
    - objectName: fabric-client-id
      key: FABRIC_CLIENT_ID
    - objectName: fabric-client-secret
      key: FABRIC_CLIENT_SECRET
    - objectName: fabric-tenant-id
      key: FABRIC_TENANT_ID
